'use client';
import {useEffect,useState} from 'react';
import BookingDetails from './BookingDetails';
type Catalog={nome:string;services:{id:string;nome:string;durata:number;prezzo:number|null}[];operators:{id:string;nome:string;services:string[]}[]};
type Props={catalog:Catalog;today:string;initial:{service:string;operator:string;date:string};availability:(s:string,o:string,d:string)=>Promise<{slots:{start_at:string}[];error:boolean}>;action:(f:FormData)=>Promise<void>};
export default function BookingWizard({catalog,today,initial,availability,action}:Props){
 const [step,setStep]=useState(1),[sid,S]=useState(initial.service),[oid,O]=useState(initial.operator),[date,D]=useState(initial.date),[slots,L]=useState<{start_at:string}[]>([]),[selected,T]=useState(''),[loading,B]=useState(false),[error,E]=useState(false),[retry,R]=useState(0);
 const [draft,setDraft]=useState<Record<string,string>>({});
 const service=catalog.services.find(s=>s.id===sid),operators=catalog.operators.filter(o=>o.services.includes(sid)),operator=operators.find(o=>o.id===oid);
 useEffect(()=>{let active=true;if(step!==2||!service||!operator||!date){B(false);return;}L([]);T('');B(true);E(false);availability(sid,oid,date).then(r=>{if(active){L(r.slots);E(r.error);B(false);}}).catch(()=>{if(active){E(true);B(false);}});return()=>{active=false;};},[step,sid,oid,date,retry,availability]);
 const move=(n:number)=>{setStep(n);window.scrollTo({top:0,behavior:'smooth'});};
 if(step===3&&service&&operator&&selected)return <BookingDetails action={action} service={service} operator={operator} date={date} slots={[{start_at:selected}]} draft={draft} saveDraft={setDraft} back={()=>move(2)}/>;
 return <section className="settings-card"><span className="booking-eyebrow">PASSAGGIO {step} DI 4</span>{step===1?<><h2>Scegli il servizio</h2><div className="service-grid">{catalog.services.map(s=><label className="service-choice" key={s.id}><input type="radio" name="service" checked={s.id===sid} onChange={()=>{S(s.id);if(!catalog.operators.some(o=>o.id===oid&&o.services.includes(s.id)))O('');}}/><span><strong>{s.nome}</strong><small>{s.durata} minuti</small>{s.prezzo!==null&&<b>{new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(s.prezzo/100)}</b>}</span></label>)}</div><button className="btn btn-primary" disabled={!service} onClick={()=>{if(!operator&&operators.length)O(operators[0].id);move(2);}}>Continua</button></>:<><h2>Con chi e quando?</h2><p>{service?.nome} · {service?.durata} minuti</p><div className="field"><label htmlFor="operator">Operatore</label><select id="operator" value={oid} onChange={e=>{O(e.target.value);T('');L([]);}}><option value="">Scegli un operatore</option>{operators.map(o=><option key={o.id} value={o.id}>{o.nome}</option>)}</select></div><div className="field"><label htmlFor="date">Giorno</label><input id="date" type="date" min={today} max={new Date(new Date(today+'T12:00:00Z').getTime()+60*86400000).toISOString().slice(0,10)} value={date} onChange={e=>{D(e.target.value);T('');L([]);}}/></div><p>Orari italiani. Prenotazioni entro i prossimi 60 giorni.</p><div aria-live="polite">{loading?<p>Sto cercando gli orari disponibili…</p>:error?<><p role="alert">Impossibile leggere gli orari.</p><button className="btn btn-secondary" onClick={()=>R(n=>n+1)}>Riprova</button></>:operator&&date&&!slots.length?<p>Nessun orario disponibile. Cambia giorno o operatore.</p>:null}</div><div className="slot-grid">{slots.map(s=><label className="slot-choice" key={s.start_at}><input type="radio" name="start" checked={selected===s.start_at} onChange={()=>T(s.start_at)}/><span>{new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',hour:'2-digit',minute:'2-digit'}).format(new Date(s.start_at))}</span></label>)}</div><button className="btn btn-primary" disabled={loading||error||!selected} onClick={()=>move(3)}>Continua</button><button className="btn btn-secondary" onClick={()=>move(1)}>Indietro al servizio</button></>}</section>;
}
