'use client';
import {useEffect,useMemo,useState} from 'react';
import BookingDetails from './BookingDetails';
type Catalog={nome:string;services:{id:string;nome:string;durata:number;prezzo:number|null}[];operators:{id:string;nome:string;services:string[]}[]};
type Props={catalog:Catalog;today:string;initial:{service:string;operator:string;date:string};profile:{nome:string;cognome:string;telefono:string};availability:(s:string,o:string,d:string)=>Promise<{slots:{start_at:string}[];error:boolean}>;action:(f:FormData)=>Promise<void>};
const euro=(n:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n/100);
export default function BookingWizard({catalog,today,initial,profile,availability,action}:Props){
 const [step,setStep]=useState(initial.service?2:1),[sid,setSid]=useState(initial.service),[oid,setOid]=useState(initial.operator),[date,setDate]=useState(initial.date),[month,setMonth]=useState(()=>new Date((initial.date||today)+'T12:00:00')),[slots,setSlots]=useState<{start_at:string}[]>([]),[selected,setSelected]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(false);
 const service=catalog.services.find(s=>s.id===sid);const operators=catalog.operators.filter(o=>o.services.includes(sid));const operator=operators.find(o=>o.id===oid);
 useEffect(()=>{let live=true;if(step!==4||!service||!operator||!date)return;setLoading(true);setError(false);setSlots([]);availability(sid,oid,date).then(r=>{if(live){setSlots(r.slots);setError(r.error);setLoading(false)}}).catch(()=>{if(live){setError(true);setLoading(false)}});return()=>{live=false}},[step,sid,oid,date,service,operator,availability]);
 const days=useMemo(()=>{const y=month.getFullYear(),m=month.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,total=new Date(y,m+1,0).getDate();return [...Array(first).fill(null),...Array.from({length:total},(_,i)=>i+1)]},[month]);
 const iso=(day:number)=>`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
 const chooseService=(id:string)=>{setSid(id);setOid('');setStep(2);window.scrollTo(0,0)};
 const chooseOperator=(id:string)=>{setOid(id||operators[0]?.id||'');setStep(3);window.scrollTo(0,0)};
 const chooseDate=(d:string)=>{setDate(d);setStep(4);window.scrollTo(0,0)};
 const steps=<><p className="step-copy">Passaggio {step} di 5</p><div className="progress-five">{[1,2,3,4,5].map(n=><span key={n} className={n<=step?'on':''}/>)}</div></>;
 if(step===5&&service&&operator&&selected)return <BookingDetails action={action} service={service} operator={operator} date={date} start={selected} profile={profile} back={()=>setStep(4)}/>;
 return <section className="wizard-body">{steps}
 {step===1&&<><h2>Cosa desideri?</h2><p>Scegli il servizio: gli orari mostrati dipenderanno dalla durata.</p><div className="choice-stack">{catalog.services.map(s=><button key={s.id} onClick={()=>chooseService(s.id)}><span><strong>{s.nome}</strong><small>{s.durata} min{s.prezzo!==null?` · ${euro(s.prezzo)}`:''}</small></span><b>›</b></button>)}</div></>}
 {step===2&&<><h2>Con chi?</h2><p>Scegli un professionista oppure lascia decidere a noi.</p><div className="choice-stack"><button onClick={()=>chooseOperator('')}><span><strong>Primo disponibile</strong><small>Ti proponiamo il primo orario libero</small></span><b>›</b></button>{operators.map(o=><button key={o.id} onClick={()=>chooseOperator(o.id)}><i>{o.nome.charAt(0)}</i><strong>{o.nome}</strong><b>›</b></button>)}</div></>}
 {step===3&&<><h2>Quando?</h2><p>{service?.nome} · {operator?.nome}</p><div className="calendar-head"><button disabled={month<=new Date(today+'T12:00:00')} onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><strong>{new Intl.DateTimeFormat('it-IT',{month:'long',year:'numeric'}).format(month)}</strong><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div><div className="calendar-week">{['LUN','MAR','MER','GIO','VEN','SAB','DOM'].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-grid">{days.map((d,i)=>d===null?<span key={`e${i}`}/>:<button key={d} disabled={iso(d)<today||new Date(month.getFullYear(),month.getMonth(),d).getDay()===0} onClick={()=>chooseDate(iso(d))} className={iso(d)===date?'selected':''}>{d}<i/></button>)}</div><p className="calendar-legend">● Giorno disponibile</p></>}
 {step===4&&<><h2>A che ora?</h2><p>{new Intl.DateTimeFormat('it-IT',{dateStyle:'full'}).format(new Date(date+'T12:00:00'))} · {service?.nome} · {operator?.nome}</p>{loading?<p>Sto cercando gli orari disponibili…</p>:error?<p role="alert">Impossibile leggere gli orari. Torna indietro e riprova.</p>:!slots.length?<p>Nessun orario disponibile per questo giorno.</p>:['MATTINA','POMERIGGIO'].map((label,index)=>{const group=slots.filter(s=>(new Date(s.start_at).toLocaleString('it-IT',{timeZone:'Europe/Rome',hour:'2-digit',hour12:false})<'14')===!index);return group.length?<div className="time-section" key={label}><p>{label}</p><div className="time-grid">{group.map(s=><button key={s.start_at} onClick={()=>{setSelected(s.start_at);setStep(5)}}>{new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',hour:'2-digit',minute:'2-digit'}).format(new Date(s.start_at))}</button>)}</div></div>:null})}</>}
 {step>1&&<button className="wizard-back" onClick={()=>setStep(step-1)}>‹ Torna indietro</button>}
 </section>;
}
