import Link from 'next/link';
import {redirect} from 'next/navigation';
import {revalidatePath} from 'next/cache';
import {createServerClient} from '@/lib/supabase/server';
type Booking={id:string;start:string;end:string;stato:string;service:string;operator:string};
export default async function Appointments({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{tab?:string;saved?:string;error?:string}>}){
 const {slug}=await params;const q=await searchParams;const db=await createServerClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect(`/cliente/${slug}/login`);const {data,error}=await db.rpc('prenow_customer_appointments',{p_slug:slug});
 async function cancel(f:FormData){'use server';const db=await createServerClient();const r=await db.rpc('prenow_customer_cancel',{p_slug:slug,p_booking:String(f.get('id'))});if(r.error||!r.data)redirect(`/cliente/${slug}/appuntamenti?error=1`);revalidatePath(`/cliente/${slug}/appuntamenti`);redirect(`/cliente/${slug}/appuntamenti?saved=1`);}
 const rows=(data||[]) as Booking[],future=q.tab!=='storico';const filtered=rows.filter(a=>future?new Date(a.start)>new Date()&&a.stato==='confermato':new Date(a.start)<=new Date()||a.stato!=='confermato');
 const day=(d:string)=>new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',weekday:'long',day:'numeric',month:'long'}).format(new Date(d));const time=(d:string)=>new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',hour:'2-digit',minute:'2-digit'}).format(new Date(d));
 return <main className="claude-page"><header className="claude-titlebar"><Link href={`/cliente/${slug}`} className="round-back">‹</Link><h1>I miei appuntamenti</h1></header><section className="appointments-body"><div className="tabs"><Link className={future?'active':''} href={`/cliente/${slug}/appuntamenti`}>Prossimi</Link><Link className={!future?'active':''} href={`/cliente/${slug}/appuntamenti?tab=storico`}>Storico</Link></div>{q.saved&&<p role="status">Appuntamento cancellato.</p>}{q.error&&<p role="alert">Cancellazione non riuscita.</p>}{error?<p>Impossibile caricare gli appuntamenti.</p>:!filtered.length?<div className="claude-card empty-bookings"><p>Nessun appuntamento in questa sezione.</p><Link className="claude-primary" href={`/cliente/${slug}/prenota`}>Prenota ora</Link></div>:filtered.map(a=><article className="appointment-card" key={a.id}><span className="status-pill">{a.stato==='confermato'?'Confermato':'Concluso'}</span><strong className="appointment-time">{time(a.start)}</strong><h2>{day(a.start)}</h2><p>{a.service} · {a.operator} · {Math.round((new Date(a.end).getTime()-new Date(a.start).getTime())/60000)} min</p>{future&&<div className="appointment-actions"><Link href={`/cliente/${slug}/prenota`} className="claude-secondary">Modifica</Link><form action={cancel}><input type="hidden" name="id" value={a.id}/><button className="cancel-button">Cancella</button></form></div>}</article>)}</section></main>;
}
