'use client';
import {useState} from 'react';
import {saveHours,saveOwnerSettings,saveService} from './actions';

type Service={id:string;nome:string;durata_min:number;prezzo_centesimi:number|null;ordine:number;attivo:boolean};
type Hours={id:string;weekday:number;chiuso:boolean;fasce:Array<{da:string;a:string}>};
const days=['Domenica','Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato'];

export default function SettingsManager({slug,tenant,settings,branding,services,hours}:{slug:string;tenant:any;settings:any;branding:any;services:Service[];hours:Hours[]}){
 const [tab,setTab]=useState<'activity'|'services'|'hours'>('activity'),[service,setService]=useState<Service|null|undefined>(undefined),[day,setDay]=useState<Hours|null>(null);
 return <><div className="owner-tabs"><button className={tab==='activity'?'active':''} onClick={()=>setTab('activity')}>Attività</button><button className={tab==='services'?'active':''} onClick={()=>setTab('services')}>Servizi</button><button className={tab==='hours'?'active':''} onClick={()=>setTab('hours')}>Orari</button></div>
 {tab==='activity'&&<section className="owner-panel"><div className="owner-panel-head"><div><h2>Attività e contatti</h2><p>Informazioni pubbliche mostrate ai clienti.</p></div></div><form action={saveOwnerSettings} className="owner-form"><input type="hidden" name="slug" value={slug}/><input type="hidden" name="logo_url" value={branding.logo_url||''}/><input type="hidden" name="color_primary" value={branding.color_primary||'#7c6ff0'}/><input type="hidden" name="color_bg" value={branding.color_bg||'#101218'}/><input type="hidden" name="color_text" value={branding.color_text||'#ecedf1'}/><div className="owner-form-grid"><label>Nome attività<input name="nome" defaultValue={tenant.nome||''} required/></label><label>Email pubblica<input name="email" type="email" defaultValue={settings.email||''}/></label><label>Telefono<input name="telefono" defaultValue={settings.telefono||''}/></label><label>WhatsApp<input name="whatsapp" defaultValue={settings.whatsapp||''}/></label><label className="wide">Descrizione<textarea name="descrizione" defaultValue={settings.descrizione||''}/></label><label className="wide">Indirizzo<input name="via" defaultValue={settings.via||''}/></label><label>CAP<input name="cap" defaultValue={settings.cap||''}/></label><label>Città<input name="citta" defaultValue={settings.citta||''}/></label><label>Provincia<input name="provincia" defaultValue={settings.provincia||''}/></label><label>Link indicazioni<input name="maps_url" type="url" defaultValue={settings.maps_url||''}/></label><label>Sito web<input name="sito_web" type="url" defaultValue={settings.sito_web||''}/></label><label>Instagram<input name="instagram" type="url" defaultValue={settings.instagram||''}/></label><label>Facebook<input name="facebook" type="url" defaultValue={settings.facebook||''}/></label></div><p className="owner-info-note">Logo e colori dell’app vengono gestiti dal configuratore Branding della Dashboard Super Admin Prenow.</p><button className="owner-primary">Salva impostazioni</button></form></section>}
 {tab==='services'&&<section><button className="owner-primary owner-full-mobile" onClick={()=>setService(null)}>+ Nuovo servizio</button><div className="owner-panel owner-compact-list">{services.map(s=><button key={s.id} className="owner-list-row" onClick={()=>setService(s)}><div><b>{s.nome}</b><span>{s.durata_min} min · {s.prezzo_centesimi==null?'Prezzo non indicato':`€${(s.prezzo_centesimi/100).toFixed(0)}`}</span></div><em className={s.attivo?'ok':'muted'}>{s.attivo?'Attivo':'Non attivo'}</em></button>)}</div></section>}
 {tab==='hours'&&<section className="owner-panel owner-compact-list">{hours.slice().sort((a,b)=>((a.weekday+6)%7)-((b.weekday+6)%7)).map(h=><button key={h.id} className="owner-day-row" onClick={()=>setDay(h)}><div><b>{days[h.weekday]}</b><span className={h.chiuso?'closed':''}>{h.chiuso?'Chiuso':h.fasce.map(f=>`${f.da}–${f.a}`).join(', ')||'Orario non impostato'}</span></div><i>›</i></button>)}</section>}
 {service!==undefined&&<Modal title={service?'Modifica servizio':'Nuovo servizio'} close={()=>setService(undefined)}><form action={saveService} className="owner-form"><input type="hidden" name="slug" value={slug}/><input type="hidden" name="id" value={service?.id||''}/><label>Nome<input name="nome" defaultValue={service?.nome||''} required/></label><div className="owner-time"><label>Durata<input name="durata" type="number" min="15" step="15" defaultValue={service?.durata_min||30} required/></label><label>Prezzo €<input name="prezzo" inputMode="decimal" defaultValue={service?.prezzo_centesimi==null?'':(service.prezzo_centesimi/100).toFixed(2)}/></label></div><label>Ordine<input name="ordine" type="number" defaultValue={service?.ordine||0}/></label><label className="check"><input name="attivo" type="checkbox" defaultChecked={service?.attivo??true}/> Attivo</label><button className="owner-primary">Salva servizio</button></form></Modal>}
 {day&&<DayModal slug={slug} value={day} close={()=>setDay(null)}/>}</>;
}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="owner-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><section className="owner-modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button onClick={close} aria-label="Chiudi">×</button></header>{children}</section></div>}
function DayModal({slug,value,close}:{slug:string;value:Hours;close:()=>void}){const [closed,setClosed]=useState(value.chiuso),[ranges,setRanges]=useState(value.fasce.length?value.fasce:[{da:'09:00',a:'13:00'}]);return <Modal title={days[value.weekday]} close={close}><form action={saveHours} className="owner-form"><input type="hidden" name="slug" value={slug}/><input type="hidden" name="id" value={value.id}/><input type="hidden" name="weekday" value={value.weekday}/><label className="owner-switch-row">Chiuso<input type="checkbox" name="chiuso" checked={closed} onChange={e=>setClosed(e.target.checked)}/></label>{!closed&&<>{ranges.map((f,i)=><div className="owner-range-row" key={i}><input type="time" name="da" value={f.da} onChange={e=>setRanges(ranges.map((x,n)=>n===i?{...x,da:e.target.value}:x))}/><span>–</span><input type="time" name="a" value={f.a} onChange={e=>setRanges(ranges.map((x,n)=>n===i?{...x,a:e.target.value}:x))}/><button type="button" onClick={()=>setRanges(ranges.filter((_,n)=>n!==i))}>×</button></div>)}<button type="button" className="owner-add-range" onClick={()=>setRanges([...ranges,{da:'09:00',a:'13:00'}])}>+ Aggiungi fascia oraria</button></>}<button className="owner-primary">Salva</button></form></Modal>}
