import Link from 'next/link';
import {notFound} from 'next/navigation';
import {requireTenantManager} from '@/lib/owner-auth';
import {createServerClient} from '@/lib/supabase/server';
import {addOperatorAbsence,deleteOperatorAbsence,removeOperator,saveOperatorData,saveStaffAccess} from '../actions';
import {OperatorHours,OperatorServices,OperatorStatus} from './OperatorControls';
export const dynamic='force-dynamic';
type Member={operator_id:string;membership_id:string|null;nome:string;cognome:string|null;email:string|null;telefono:string|null;ruolo:'staff'|'operator';attivo:boolean;services:string[]};
type TimeRange={da:string;a:string};type Hours={weekday:number;chiuso:boolean;fasce:(TimeRange|string[])[]};type Absence={id:string;data_inizio:string;data_fine:string;motivo:string|null};

export default async function OperatorDetail({params,searchParams}:{params:Promise<{slug:string;id:string}>;searchParams:Promise<{tab?:string;saved?:string;error?:string}>}){
 const {slug,id}=await params,q=await searchParams,ctx=await requireTenantManager(slug),db=await createServerClient();
 const [{data:all},{data:services},{data:hours},{data:standard},{data:absences}]=await Promise.all([db.rpc('prenow_owner_staff',{p_slug:slug}),db.from('services').select('id,nome').eq('tenant_id',ctx.tenant_id).eq('attivo',true).order('ordine').order('created_at'),db.from('business_hours').select('weekday,chiuso,fasce').eq('tenant_id',ctx.tenant_id).eq('operator_id',id),db.from('business_hours').select('weekday,chiuso,fasce').eq('tenant_id',ctx.tenant_id).is('operator_id',null),db.from('operator_absences').select('id,data_inizio,data_fine,motivo').eq('tenant_id',ctx.tenant_id).eq('operator_id',id).gte('data_fine',new Date().toISOString().slice(0,10)).order('data_inizio')]);
 const member=((all||[]) as Member[]).find(x=>x.operator_id===id);if(!member)notFound();
 const tab=['dati','servizi','permessi','orari','assenze'].includes(q.tab||'')?q.tab!:'dati',hourMap=new Map<number,Hours>();(standard||[]).forEach(x=>hourMap.set(x.weekday,x as Hours));(hours||[]).forEach(x=>hourMap.set(x.weekday,x as Hours));
 return <><p className="owner-detail-back"><Link href={`/titolare/${slug}/impostazioni?tab=operatori`}>← Operatori</Link></p><div className="owner-operator-header"><div className="owner-avatar owner-avatar-large">{member.nome.charAt(0)}</div><div><h1>{member.nome} {member.cognome||''}</h1><p>{member.email||'Accesso non ancora collegato'}</p></div><OperatorStatus slug={slug} id={id} active={member.attivo}/></div>
 {q.saved?<p className="owner-alert success">Modifiche salvate.</p>:null}{q.error?<p className="owner-alert error">Operazione non completata. Controlla i dati.</p>:null}
 <nav className="owner-tabs owner-operator-tabs">{['dati','servizi','permessi','orari','assenze'].map(item=><Link key={item} className={tab===item?'active':''} href={`?tab=${item}`}>{item.charAt(0).toUpperCase()+item.slice(1)}</Link>)}</nav>
 {tab==='dati'?<><form action={saveOperatorData} className="owner-panel owner-staff-card owner-form"><input type="hidden" name="slug" value={slug}/><input type="hidden" name="operator_id" value={id}/><div className="owner-form-grid"><label>Nome<input name="nome" required defaultValue={member.nome}/></label><label>Cognome<input name="cognome" defaultValue={member.cognome||''}/></label><label>Email<input name="email" type="email" defaultValue={member.email||''}/></label><label>Telefono<input name="telefono" defaultValue={member.telefono||''}/></label></div><button className="owner-primary">Salva dati</button></form><form action={removeOperator} className="owner-remove-form"><input type="hidden" name="slug" value={slug}/><input type="hidden" name="operator_id" value={id}/><button className="owner-danger-button">Rimuovi operatore</button></form></>:null}
 {tab==='servizi'?<OperatorServices slug={slug} id={id} services={services||[]} assigned={member.services}/>:null}
 {tab==='permessi'?<form action={saveStaffAccess} className="owner-panel owner-staff-card owner-form"><input type="hidden" name="slug" value={slug}/><input type="hidden" name="operator_id" value={id}/><input type="hidden" name="membership_id" value={member.membership_id||''}/><input type="hidden" name="nome" value={member.nome}/><input type="hidden" name="cognome" value={member.cognome||''}/><input type="hidden" name="email" value={member.email||''}/><input type="hidden" name="telefono" value={member.telefono||''}/><input type="hidden" name="attivo" value={member.attivo?'on':''}/>{member.services.map(s=><input key={s} type="hidden" name="services" value={s}/>)}<p className="owner-permission-note">Cosa può fare {member.nome} nell’app di gestione.</p><label className={`owner-perm-card ${member.ruolo==='operator'?'selected':''}`}><input type="radio" name="ruolo" value="operator" defaultChecked={member.ruolo==='operator'}/><b>Base</b><span>Vede solo la propria agenda e i propri appuntamenti. Può segnare completato o assente.</span></label><label className={`owner-perm-card ${member.ruolo==='staff'?'selected':''}`}><input type="radio" name="ruolo" value="staff" defaultChecked={member.ruolo==='staff'}/><b>Gestione</b><span>Come Base, più: gestisce servizi e prezzi, operatori, agende, orari, clienti e impostazioni.</span></label><button className="owner-primary">Salva permesso</button></form>:null}
 {tab==='orari'?<OperatorHours slug={slug} id={id} hours={[...hourMap.values()]}/>:null}
 {tab==='assenze'?<><form action={addOperatorAbsence} className="owner-panel owner-staff-card owner-form"><input type="hidden" name="slug" value={slug}/><input type="hidden" name="operator_id" value={id}/><div className="owner-form-grid"><label>Data inizio<input required type="date" name="data_inizio"/></label><label>Data fine<input required type="date" name="data_fine"/></label><label className="wide">Motivo<input name="motivo" maxLength={500}/></label></div><button className="owner-primary">+ Aggiungi assenza</button></form><section className="owner-panel owner-compact-list">{(absences as Absence[]||[]).map(a=><div className="owner-list-row" key={a.id}><div><b>{a.data_inizio} – {a.data_fine}</b><span>{a.motivo||'Nessun motivo indicato'}</span></div><form action={deleteOperatorAbsence}><input type="hidden" name="slug" value={slug}/><input type="hidden" name="operator_id" value={id}/><input type="hidden" name="absence_id" value={a.id}/><button className="owner-danger-link">Elimina</button></form></div>)}</section></>:null}</>;
}
